name: Windows-10-Cloudflare
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Prepare RDP User
      shell: powershell
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        $Password = ConvertTo-SecureString "MyRobloxBot123!" -AsPlainText -Force
        if (Get-LocalUser -Name "runneradmin" -ErrorAction SilentlyContinue) {
            Set-LocalUser -Name "runneradmin" -Password $Password
        } else {
            New-LocalUser "runneradmin" -Password $Password -Description "RDP"
            Add-LocalGroupMember -Group "Administrators" -Member "runneradmin"
        }

    - name: Start Tunnel
      shell: powershell
      run: |
        curl.exe -L -o cloudflared.exe https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe
        Write-Host "--- GENERATING TUNNEL LINK ---"
        Start-Process ./cloudflared.exe -ArgumentList "tunnel --url rdp://localhost:3389"
        Start-Sleep -Seconds 20
        Get-Content -Path "cloudflared.log" -ErrorAction SilentlyContinue | Select-String "trycloudflare.com"
        
        # Keep Alive Loop
        $i = 0; while($i -le 360) { Start-Sleep -Seconds 60; $i++ }
